version: "3"
services:
  mysql:
    image: mariadb:10.6.4
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: grapevine_rss
      MYSQL_USER: grapevine
      MYSQL_PASSWORD: rss
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  mysql-test:
    image: mariadb:10.6.4
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: grapevine_rss
      MYSQL_USER: grapevine
      MYSQL_PASSWORD: test
    ports:
      - 3307:3306

volumes:
  mysql: {}
