CREATE TABLE IF NOT EXISTS `feeds`(
  id INT(11) NOT NULL AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  url VARCHAR(500) NOT NULL,
  lastUpdated INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
) engine=InnoDB DEFAULT CHARACTER SET=utf8mb4;
